### ISSUE TITLE
Add database

### ISSUE THREAD

**Issue by nelsonnyland** [nelsonnyland/WorldwideMovieDatabase#1]
We need to connect our project up to a database (e.g. Entity Framework).

My suggestion is to make it code-first so we have more automation.

One alternative is to just use ADO.NET, but that would require more maintenance and less automation.

**Comment by juanarbol** [comment]
I could work on this one, what do you think about firebase? It's extremely cheap and easy.

**Comment by nelsonnyland** [comment]
That sounds great. We are using ASP.NET MVC with a T-SQL database as noted above, possibly using Entity Framework. Just so you know, this is a class project for school, but my instructor is fine with anyone contributing - so you're good. 👍

**Comment by juanarbol** [comment]
Uhh, I haven't use ASP.NET in my life... It could take me more time than expected, no problem with that?

**Comment by juanarbol** [comment]
Angular, React and Node.

**Comment by nelsonnyland** [comment]
Alright, well I've never worked with Angular, but if you have some experience with Javascript then maybe we could put together a website. If you come up with the boilerplate code (the basic starter code), then I might be able to contribute on your Github. In any case, it can't hurt to try new things!

**Comment by juanarbol** [comment]
Ok! I'd recommend use hangout for make a more clear planning... Be more synchronised just while we start project structure
