### ISSUE TITLE
Modify default shared layout to match mock up

### ISSUE THREAD

**Issue by MrDrennan** [nelsonnyland/WorldwideMovieDatabase#29]
![wmdhomepagemockup](https://user-images.githubusercontent.com/31075105/47043707-20511980-d143-11e8-8496-ee783e3ce26c.PNG)

**Comment by nelsonnyland** [comment]
![2018_10_23](https://user-images.githubusercontent.com/29189956/47406585-e7e5a880-d70b-11e8-8d3d-8a5097e26e79.JPG)
Making headway...
